# -*- coding: utf-8 -*-
from __future__ import annotations

import ctypes
import os
import shutil
import subprocess
import sys
import uuid
from pathlib import Path

APP_NAME = "NEVIS MEP"
COMPANY_KEY = "57535711"
INSTALL_DIR = Path(r"C:\NEVIS MEP")
PROGRAM_DATA_DIR = Path(os.environ.get("PROGRAMDATA", r"C:\ProgramData")) / APP_NAME


def _payload_dir() -> Path:
    base = Path(getattr(sys, "_MEIPASS", Path(__file__).resolve().parent))
    return base / "payload" / "NEVIS_MEP"


def _message(title: str, text: str, flags: int = 0x40) -> None:
    try:
        ctypes.windll.user32.MessageBoxW(None, text, title, flags)
    except Exception:
        print(f"{title}\n{text}")


def _is_admin() -> bool:
    try:
        return bool(ctypes.windll.shell32.IsUserAnAdmin())
    except Exception:
        return False


def _iter_payload_files(src: Path):
    for path in src.rglob("*"):
        if path.is_file():
            yield path


def _copy_payload(src: Path, dst: Path, progress=None) -> None:
    if not src.exists():
        raise FileNotFoundError(f"Payload not found: {src}")
    files = list(_iter_payload_files(src))
    total = max(1, len(files))
    dst.mkdir(parents=True, exist_ok=True)
    for idx, f in enumerate(files, start=1):
        rel = f.relative_to(src)
        target = dst / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        if progress:
            progress(idx, total, f"Copying {rel}")
        shutil.copy2(f, target)


def _ensure_install_id(app_dir: Path, program_data: Path) -> None:
    app_dir.mkdir(parents=True, exist_ok=True)
    program_data.mkdir(parents=True, exist_ok=True)
    app_id = app_dir / "install_id.dat"
    pd_id = program_data / "install_id.dat"
    install_id = ""
    for p in (app_id, pd_id):
        try:
            v = p.read_text(encoding="utf-8-sig").strip()
            if v:
                install_id = v
                break
        except Exception:
            pass
    if not install_id:
        install_id = uuid.uuid4().hex
    app_id.write_text(install_id, encoding="ascii")
    pd_id.write_text(install_id, encoding="ascii")
    # Reinstall/update should not keep stale activation generated by an older
    # build or by a previous hardware fingerprint routine. The app will create a
    # fresh machine-bound activation on first launch.
    for p in (app_dir / "activation.dat", program_data / "activation.dat"):
        try:
            if p.exists():
                p.unlink()
        except Exception:
            pass


def _make_shortcut(link_path: Path, target: Path, workdir: Path, icon: Path) -> None:
    link_path.parent.mkdir(parents=True, exist_ok=True)
    ps = f"""
$ws = New-Object -ComObject WScript.Shell
$s = $ws.CreateShortcut('{str(link_path).replace("'", "''")}')
$s.TargetPath = '{str(target).replace("'", "''")}'
$s.WorkingDirectory = '{str(workdir).replace("'", "''")}'
$s.IconLocation = '{str(icon).replace("'", "''")}'
$s.Save()
"""
    subprocess.run(
        ["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", ps],
        check=False,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )


def _create_shortcuts(app_dir: Path) -> None:
    exe = app_dir / "Nevis.exe"
    editor = app_dir / "Nevis_Library_Editor.exe"
    icon = app_dir / "Ico" / "icon_tan.ico"
    desktop = Path(os.environ.get("PUBLIC", r"C:\Users\Public")) / "Desktop"
    start = Path(os.environ.get("PROGRAMDATA", r"C:\ProgramData")) / r"Microsoft\Windows\Start Menu\Programs\NEVIS MEP"
    _make_shortcut(desktop / "NEVIS MEP.lnk", exe, app_dir, icon)
    _make_shortcut(start / "NEVIS MEP.lnk", exe, app_dir, icon)
    _make_shortcut(start / "NEVIS Library Editor.lnk", editor, app_dir, icon)


class NevisInstallerUI:
    def __init__(self):
        import tkinter as tk
        from tkinter import messagebox, ttk

        self.tk = tk
        self.ttk = ttk
        self.messagebox = messagebox
        self.root = tk.Tk()
        self.root.title("NEVIS MEP Setup")
        self.root.geometry("520x330")
        self.root.resizable(False, False)
        self.root.configure(bg="#F4F7FA")

        icon = _payload_dir() / "Ico" / "icon_tan.ico"
        try:
            if icon.exists():
                self.root.iconbitmap(str(icon))
        except Exception:
            pass

        self._build()

    def _build(self):
        tk = self.tk
        ttk = self.ttk

        title = tk.Label(
            self.root,
            text="NEVIS MEP",
            font=("Segoe UI", 20, "bold"),
            fg="#163B66",
            bg="#F4F7FA",
        )
        title.pack(pady=(22, 4))

        sub = tk.Label(
            self.root,
            text="Residential drainage rolling-pipe tool / 住宅排水転がし配管専用",
            font=("Segoe UI", 9),
            fg="#C55A00",
            bg="#F4F7FA",
        )
        sub.pack(pady=(0, 18))

        panel = tk.Frame(self.root, bg="#FFFFFF", highlightbackground="#C9D3DF", highlightthickness=1)
        panel.pack(fill="x", padx=28, pady=(0, 14))

        tk.Label(
            panel,
            text="Company key / 会社キー",
            font=("Segoe UI", 9, "bold"),
            fg="#26384D",
            bg="#FFFFFF",
        ).grid(row=0, column=0, sticky="w", padx=18, pady=(18, 6))

        self.key_var = tk.StringVar()
        self.key_entry = ttk.Entry(panel, textvariable=self.key_var, show="*", width=24)
        self.key_entry.grid(row=1, column=0, sticky="w", padx=18, pady=(0, 16))
        self.key_entry.focus_set()

        self.install_btn = ttk.Button(panel, text="Install to C:\\NEVIS MEP", command=self.install)
        self.install_btn.grid(row=1, column=1, sticky="e", padx=18, pady=(0, 16))
        panel.grid_columnconfigure(1, weight=1)

        self.progress = ttk.Progressbar(self.root, orient="horizontal", mode="determinate", maximum=100)
        self.progress.pack(fill="x", padx=28, pady=(6, 8))

        self.status_var = tk.StringVar(value="Ready. Enter company key to start installation.")
        self.status = tk.Label(
            self.root,
            textvariable=self.status_var,
            font=("Segoe UI", 8),
            anchor="w",
            fg="#526174",
            bg="#F4F7FA",
        )
        self.status.pack(fill="x", padx=28)

        note = tk.Label(
            self.root,
            text="Installer will copy all libraries, icons and the library editor.",
            font=("Segoe UI", 8),
            fg="#7A8797",
            bg="#F4F7FA",
        )
        note.pack(anchor="w", padx=28, pady=(10, 0))

        self.root.bind("<Return>", lambda _e: self.install())

    def set_status(self, text: str, percent: float | None = None):
        self.status_var.set(text)
        if percent is not None:
            self.progress["value"] = max(0, min(100, percent))
        self.root.update_idletasks()

    def install(self):
        key = self.key_var.get().strip()
        if key != COMPANY_KEY:
            self.messagebox.showerror("NEVIS MEP Setup", "Invalid company key.")
            self.key_entry.focus_set()
            self.key_entry.selection_range(0, "end")
            return

        if not _is_admin():
            self.messagebox.showwarning("NEVIS MEP Setup", "Please run this installer as Administrator.")
            return

        self.install_btn.configure(state="disabled")
        self.key_entry.configure(state="disabled")
        try:
            src = _payload_dir()
            self.set_status("Preparing installer...", 3)

            def copy_progress(idx, total, text):
                pct = 5 + (idx / max(1, total)) * 78
                self.set_status(text, pct)

            _copy_payload(src, INSTALL_DIR, copy_progress)
            self.set_status("Creating machine-bound install key...", 87)
            _ensure_install_id(INSTALL_DIR, PROGRAM_DATA_DIR)
            self.set_status("Creating shortcuts...", 94)
            _create_shortcuts(INSTALL_DIR)
            self.set_status("Installation completed.", 100)
            self.messagebox.showinfo("NEVIS MEP Setup", f"Installed successfully:\n{INSTALL_DIR}")
            self.root.destroy()
        except Exception as ex:
            self.install_btn.configure(state="normal")
            self.key_entry.configure(state="normal")
            self.set_status("Installation failed.", None)
            self.messagebox.showerror("NEVIS MEP Setup", f"Install failed:\n{ex}")

    def run(self) -> int:
        self.root.mainloop()
        return 0


def main() -> int:
    try:
        return NevisInstallerUI().run()
    except Exception as ex:
        _message(APP_NAME, f"Installer UI failed:\n{ex}", 0x10)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
